"\n``GREEN``|-(``BLUE``PGS``GREEN``)-[``RESET````CWD````GREEN``]-(``CSTATUS````GREEN``)\n|-``BLUE``>``RESET`` "
"``GREEN``|-(``BLUE``PGS``GREEN``)-[``RESET````CWD````GREEN``]-(``CSTATUS````GREEN``)\n|-``BLUE``>``RESET`` "
