"\n``GREEN``|-(``BLUE``PGS``GREEN``)-[``RESET````CWD````GREEN``]-(``RED````STATUS````GREEN``)\n|-``BLUE``>``RESET`` "
"``GREEN``|-(``BLUE``PGS``GREEN``)-[``RESET````CWD````GREEN``]-(``RED````STATUS````GREEN``)\n|-``BLUE``>``RESET`` "
