"""AST -> pigeon assembly text.

The model, from compiler/design/04-codegen.md:

  * Every expression leaves its value in A.
  * A binary operation evaluates its left side into A, parks it on the
    HARDWARE stack, evaluates its right into A, moves that to B, pops the
    left back into A, and applies the operator. The hardware stack can
    hold these because they are anonymous -- pushed and popped in matching
    order, never addressed.
  * Named storage (parameters, locals) lives on the SOFTWARE frame stack
    at [F + constant], because the machine cannot read SP.

Register roles: A accumulator, B right operand, C address scratch,
D and E scratch, F frame pointer (reserved, never allocated).
"""
from typing import List, Optional

from . import ast_nodes as A
from .typesys import (CHAR, UCHAR, VOID, ArrayType, FunctionType, StructType,
                    WORD, decays, is_integer)

FRAME_STACK_BYTES = 256 * 1024      # -fframe-size to change

# A comparison lowers to a conditional jump; the branch we take when the
# comparison is TRUE.
JUMP_FOR = {"==": "JZ", "!=": "JNZ", "<": "JL", ">": "JG", "<=": "JLE", ">=": "JGE"}

DIRECT_BINOPS = {"+": "ADD", "-": "SUB", "*": "MUL", "/": "DIV",
                 "&": "AND", "|": "OR", "^": "XOR", "<<": "SHL", ">>": "SHR"}


class CodeGen:
    def __init__(self, program: A.Program, source_lines=None):
        self.program = program
        self.source_lines = source_lines or []
        self.out: List[str] = []
        self.label_count = 0
        self.loops: List[tuple] = []       # (continue_label, break_label)
        self.function: Optional[A.FunctionDef] = None
        self.last_line = -1

    # --- emission helpers --------------------------------------------------

    def emit(self, text: str):
        self.out.append(f"    {text}")

    def label(self, name: str):
        self.out.append(f"{name}:")

    def new_label(self, hint: str = "L") -> str:
        self.label_count += 1
        return f"__{hint}{self.label_count}"

    def comment(self, text: str):
        self.out.append(f"    ; {text}")

    def trace(self, node: A.Node):
        """Interleave the C source as a comment.

        Generated assembly is the only thing you can read when the
        machine misbehaves, and the debugger shows one instruction at a
        time -- having the source line beside it is the difference between
        a tractable session and an intractable one.
        """
        if not (self.source_lines and node is not None and node.token):
            return
        line = node.token.line
        if line == self.last_line or not 1 <= line <= len(self.source_lines):
            return
        self.last_line = line
        text = self.source_lines[line - 1].strip()
        if text:
            self.out.append(f"    ; {line}: {text}")

    # --- program ------------------------------------------------------------

    def generate(self) -> str:
        self.out.append("; generated by pigeon-cc -- do not edit")
        self.out.append(".ORG PROGRAM_LOAD_ADDR")
        self.out.append("")
        self._startup()
        for function in self.program.functions:
            self._function(function)
        self._data()
        return "\n".join(self.out) + "\n"

    def _startup(self):
        """Set the frame pointer, init the heap, call main, halt."""
        self.comment("startup: establish the frame pointer, then call main")
        self.label("__start")
        self.emit("MOV F, #__frame_base")
        self.emit("MOV C, #__heap_ptr")
        self.emit("MOV A, #__heap_base")
        self.emit("MWW C, A")
        self.emit(f"CALL {self._main_label()}")
        self.emit("HALT")
        self.out.append("")

    def _main_label(self) -> str:
        for function in self.program.functions:
            if function.name == "main":
                return function.label or "main"
        return "main"

    def _data(self):
        """Globals, string literals, and the frame/heap regions."""
        self.out.append("")
        self.comment("--- static data ---")
        self.emit(f".align {WORD}")

        for label, text in self.program.strings:
            self.label(label)
            self.emit(f'.asciz "{_escape_c(text)}"')
        if self.program.strings:
            self.emit(f".align {WORD}")

        for declaration in self.program.globals:
            if declaration.is_extern:
                continue                     # defined elsewhere; no storage here
            self.label(declaration.symbol.label)
            size = declaration.decl_type.size
            if isinstance(declaration.init, A.InitList):
                element = declaration.decl_type.element
                directive = ".byte" if element.size == 1 else ".word"
                mask = 0xFF if element.size == 1 else 0xFFFFFFFF
                values = [v.label if isinstance(v, A.StringLiteral) else str(v.value & mask)
                          for v in declaration.init.values]
                for chunk in range(0, len(values), 12):
                    self.emit(f"{directive} " + ", ".join(values[chunk:chunk + 12]))
                written = len(values) * element.size
                if written < size:
                    self.emit(f".space {size - written}")
                self.emit(f".align {WORD}")
                continue
            if isinstance(declaration.init, A.StringLiteral):
                self.emit(f'.asciz "{_escape_c(declaration.init.value)}"')
                written = len(declaration.init.value) + 1
                if written < size:
                    self.emit(f".space {size - written}")
                self.emit(f".align {WORD}")
                continue
            if declaration.init is not None and isinstance(declaration.init, A.IntLiteral):
                if size == 1:
                    self.emit(f".byte {declaration.init.value & 0xFF}")
                else:
                    self.emit(f".word {declaration.init.value}")
                    if size > WORD:
                        self.emit(f".space {size - WORD}")
            else:
                self.emit(f".space {max(size, 1)}")
            self.emit(f".align {WORD}")

        self.label("__heap_ptr")
        self.emit(".word 0")
        self.label("__free_list")
        self.emit(".word 0")

        self.out.append("")
        self.comment("The frame stack and heap are ADDRESSES, not stored bytes.")
        self.comment("Reserving them with .space would put a quarter-megabyte of")
        self.comment("zeros in the image and make every boot copy it. RAM is")
        self.comment("already zero, so they just live past the end of the program.")
        self.emit(f"__frame_base  = HEAP_START")
        self.emit(f"__frame_limit = __frame_base + {FRAME_STACK_BYTES}")
        self.emit(f"__heap_base   = __frame_limit")

    # --- functions ----------------------------------------------------------

    def _function(self, function: A.FunctionDef):
        self.function = function
        self.last_line = -1
        params = ", ".join(f"{p.type} {p.name}" for p in function.params)
        self.comment(f"{function.returns} {function.name}({params})"
                     f"  frame_size={function.frame_size}")
        self.label(function.label or function.name)
        self._statement(function.body)
        # A function that falls off the end still has to return; A is
        # whatever the last expression left there.
        self.emit("RET")
        self.out.append("")
        self.function = None

    # --- statements ---------------------------------------------------------

    def _statement(self, node: A.Node):
        if node is None:
            return
        self.trace(node)
        getattr(self, f"_s_{type(node).__name__}")(node)

    def _s_Block(self, node):
        for statement in node.statements:
            self._statement(statement)

    def _s_Empty(self, node):
        pass

    def _s_VarDecl(self, node):
        if node.init is None:
            return
        self._expr(node.init)
        self._store_to_frame(node.symbol.offset, node.decl_type)

    def _s_ExprStatement(self, node):
        self._expr(node.expr)

    def _s_Return(self, node):
        if node.value is not None:
            self._expr(node.value)
        self.emit("RET")

    def _s_If(self, node):
        else_label = self.new_label("else")
        end_label = self.new_label("endif")
        self._branch_if_false(node.condition, else_label)
        self._statement(node.then)
        if node.otherwise is not None:
            self.emit(f"JMP {end_label}")
        self.label(else_label)
        if node.otherwise is not None:
            self._statement(node.otherwise)
            self.label(end_label)

    def _s_While(self, node):
        top = self.new_label("while")
        cont = self.new_label("cont")
        end = self.new_label("endwhile")
        self.loops.append((cont, end))

        self.label(top)
        if not node.is_do_while:
            self._branch_if_false(node.condition, end)
        self._statement(node.body)
        self.label(cont)
        if node.is_do_while:
            self._branch_if_true(node.condition, top)
        else:
            self.emit(f"JMP {top}")
        self.label(end)
        self.loops.pop()

    def _s_For(self, node):
        top = self.new_label("for")
        cont = self.new_label("cont")
        end = self.new_label("endfor")
        self.loops.append((cont, end))

        self._statement(node.init)
        self.label(top)
        if node.condition is not None:
            self._branch_if_false(node.condition, end)
        self._statement(node.body)
        self.label(cont)
        if node.step is not None:
            self._expr(node.step)
        self.emit(f"JMP {top}")
        self.label(end)
        self.loops.pop()

    def _s_Break(self, node):
        self.emit(f"JMP {self.loops[-1][1]}")

    def _s_Continue(self, node):
        self.emit(f"JMP {self.loops[-1][0]}")

    # --- conditions ---------------------------------------------------------

    def _branch_if_false(self, condition: A.Node, target: str):
        """Jump to `target` when `condition` is zero."""
        if isinstance(condition, A.Binary) and condition.op in JUMP_FOR:
            self._compare(condition)
            self.emit(f"{_invert(JUMP_FOR[condition.op])} {target}")
            return
        if isinstance(condition, A.Binary) and condition.op == "&&":
            self._branch_if_false(condition.left, target)
            self._branch_if_false(condition.right, target)
            return
        if isinstance(condition, A.Binary) and condition.op == "||":
            true_label = self.new_label("or")
            self._branch_if_true(condition.left, true_label)
            self._branch_if_false(condition.right, target)
            self.label(true_label)
            return
        if isinstance(condition, A.Unary) and condition.op == "!":
            self._branch_if_true(condition.operand, target)
            return

        self._expr(condition)
        self.emit("CMP A, #0")
        self.emit(f"JZ {target}")

    def _branch_if_true(self, condition: A.Node, target: str):
        if isinstance(condition, A.Binary) and condition.op in JUMP_FOR:
            self._compare(condition)
            self.emit(f"{JUMP_FOR[condition.op]} {target}")
            return
        if isinstance(condition, A.Unary) and condition.op == "!":
            self._branch_if_false(condition.operand, target)
            return

        self._expr(condition)
        self.emit("CMP A, #0")
        self.emit(f"JNZ {target}")

    def _compare(self, node: A.Binary):
        """Leave A and B set up so a J** reflects `node.op`.

        CMP is unsigned. For signed operands both values are biased by the
        sign bit first, which turns an unsigned compare into a signed one
        (verified across every sign combination).
        """
        imm = self._binary_operands(node)
        operand_type = getattr(node, "operand_type", None)
        if operand_type is not None and operand_type.is_signed:
            self.comment("signed compare: bias both sides, then compare unsigned")
            self.emit("XOR A, A, #0x80000000")
            if imm is None:
                self.emit("XOR B, B, #0x80000000")
            else:
                imm ^= 0x80000000
        self.emit(f"CMP A, #{imm}" if imm is not None else "CMP A, B")

    # --- expressions --------------------------------------------------------

    def _expr(self, node: A.Node):
        getattr(self, f"_e_{type(node).__name__}")(node)

    def _e_IntLiteral(self, node):
        self.emit(f"MOV A, #{node.value}")

    def _e_StringLiteral(self, node):
        self.emit(f"MOV A, #{node.label}")

    def _e_Identifier(self, node):
        symbol = node.symbol
        if isinstance(symbol.type, ArrayType) or symbol.storage == "function":
            self._address_of(node)              # arrays and functions decay
            return
        if symbol.storage in ("local", "param"):
            self._load_from_frame(symbol.offset, symbol.type)
        else:
            self.emit(f"{_load_op(symbol.type)} A, #{symbol.label}")

    def _e_Cast(self, node):
        self._expr(node.operand)
        target = node.to
        if target.size == 1 and is_integer(target):
            self.emit("AND A, A, #0xFF")        # narrowing to a byte
        elif target.size == 1:
            pass
        if target in (CHAR,) and node.operand.type.size > 1:
            pass                                 # sign extension is not modelled yet

    def _e_SizeOf(self, node):
        self.emit(f"MOV A, #{node.of_type.size}")

    def _e_Unary(self, node):
        if node.op == "&":
            self._address_of(node.operand)
            return
        if node.op == "*":
            self._expr(node.operand)
            if not isinstance(node.type, (ArrayType, StructType)):
                self.emit(f"{_load_op(node.type)} A, A")
            return
        if node.op == "!":
            done = self.new_label("not")
            self._expr(node.operand)
            self.emit("CMP A, #0")
            self.emit("MOV A, #0")
            self.emit(f"JNZ {done}")
            self.emit("MOV A, #1")
            self.label(done)
            return
        if node.op == "-":
            self._expr(node.operand)
            self.emit("MOV B, A")
            self.emit("MOV A, #0")
            self.emit("SUB A, A, B")
            return
        if node.op == "~":
            self._expr(node.operand)
            self.emit("NOT A, A")
            return
        if node.op == "+":
            self._expr(node.operand)
            return
        raise node.token.error(f"unary '{node.op}' is not implemented")

    def _binary_operands(self, node: A.Binary):
        """Leave the left operand in A, and say where the right one is.

        Returns None when the right operand landed in B, or its value when
        it is a literal the caller should encode as an immediate instead.
        Every arithmetic instruction takes `OP dst, src1, #imm` directly,
        so materialising a constant into B first costs an instruction on
        the majority of binary operations in real code -- callers must
        honour the return value rather than assuming B.

        The peephole matters too: when the right side is a constant or a
        plain variable it cannot clobber A, so the push/pop round trip
        through the hardware stack is skipped entirely.
        """
        if isinstance(node.right, A.IntLiteral):
            self._expr(node.left)
            return node.right.value
        if _is_simple(node.right):
            self._expr(node.left)
            self.emit("PUSH A")
            self._expr(node.right)
            self.emit("MOV B, A")
            self.emit("POP A")
            return
        self._expr(node.left)
        self.emit("PUSH A")
        self._expr(node.right)
        self.emit("MOV B, A")
        self.emit("POP A")

    def _e_Binary(self, node):
        if node.op == ",":
            self._expr(node.left)
            self._expr(node.right)
            return

        if node.op in ("&&", "||"):
            self._logical(node)
            return

        if node.op in JUMP_FOR:
            true_label = self.new_label("cmp")
            done = self.new_label("cmpend")
            self._compare(node)
            self.emit(f"{JUMP_FOR[node.op]} {true_label}")
            self.emit("MOV A, #0")
            self.emit(f"JMP {done}")
            self.label(true_label)
            self.emit("MOV A, #1")
            self.label(done)
            return

        scale = getattr(node, "scale", 1)
        if scale > 1:
            self._pointer_binary(node, scale)
            return

        imm = self._binary_operands(node)
        rhs = "B" if imm is None else f"#{imm}"
        if node.op == "%":
            self.comment("a % b  ==  a - (a / b) * b   (no MOD instruction)")
            self.emit(f"DIV C, A, {rhs}")
            self.emit(f"MUL C, C, {rhs}")
            self.emit("SUB A, A, C")
            return
        self.emit(f"{DIRECT_BINOPS[node.op]} A, A, {rhs}")

        difference = getattr(node, "pointer_diff", None)
        if difference and difference > 1:
            self.emit(f"DIV A, A, #{difference}")

    def _pointer_binary(self, node: A.Binary, scale: int):
        """p + i, i + p, p - i: the integer side is scaled by the element size."""
        pointer_left = decays(node.left.type).is_pointer
        pointer_side = node.left if pointer_left else node.right
        integer_side = node.right if pointer_left else node.left

        self._expr(pointer_side)
        self.emit("PUSH A")
        self._expr(integer_side)
        self._scale(scale)
        self.emit("MOV B, A")
        self.emit("POP A")
        self.emit(f"{DIRECT_BINOPS[node.op]} A, A, B")

    def _scale(self, scale: int):
        """Multiply A by an element size, preferring a shift."""
        if scale == 1:
            return
        shift = scale.bit_length() - 1
        if scale == 1 << shift:
            self.emit(f"SHL A, A, #{shift}")
        else:
            self.emit(f"MUL A, A, #{scale}")

    def _logical(self, node):
        false_label = self.new_label("false")
        done = self.new_label("logend")
        if node.op == "&&":
            self._branch_if_false(node.left, false_label)
            self._branch_if_false(node.right, false_label)
        else:
            true_label = self.new_label("true")
            self._branch_if_true(node.left, true_label)
            self._branch_if_false(node.right, false_label)
            self.label(true_label)
        self.emit("MOV A, #1")
        self.emit(f"JMP {done}")
        self.label(false_label)
        self.emit("MOV A, #0")
        self.label(done)

    def _e_Conditional(self, node):
        false_label = self.new_label("qfalse")
        done = self.new_label("qend")
        self._branch_if_false(node.condition, false_label)
        self._expr(node.then)
        self.emit(f"JMP {done}")
        self.label(false_label)
        self._expr(node.otherwise)
        self.label(done)

    def _e_Assign(self, node):
        if node.op != "=":
            # a op= b  ->  a = a op b, with the target evaluated once here
            # because none of the lvalue forms this compiler supports have
            # side effects in their address computation.
            binary = A.Binary(token=node.token, op=node.op[:-1],
                              left=node.target, right=node.value)
            binary.type = node.type
            binary.scale = getattr(node, "scale", 1)
            self._expr(binary)
        else:
            self._expr(node.value)
        self._store_to(node.target)

    def _e_IncDec(self, node):
        delta = node.scale if node.op == "++" else -node.scale
        self._expr(node.operand)
        if not node.prefix:
            self.emit("PUSH A")                 # postfix yields the OLD value
        if delta >= 0:
            self.emit(f"ADD A, A, #{delta}")
        else:
            self.emit(f"SUB A, A, #{-delta}")
        self._store_to(node.operand)
        if not node.prefix:
            self.emit("POP A")

    def _e_Call(self, node):
        frame = self.function.frame_size
        self.comment(f"call {getattr(node.callee, 'name', '<indirect>')}"
                     f" -- args go at F+{frame}, then F moves up by {frame}")

        def slot(index):
            self.emit("MOV C, F")
            offset = frame + index * WORD
            if offset:
                self.emit(f"ADD C, C, #{offset}")
            self.emit("MWW C, A")

        # A nested call does not just clobber registers -- it writes ITS
        # arguments to the SAME frame slots this call is filling in, because
        # both compute them from F plus this function's frame size. So
        # `two(7, id(3))` wrote 7 into slot 0, then id's own argument
        # overwrote it, and `two` received (3, 3).
        #
        # When a later argument can call something, park every value on the
        # hardware stack first and only then write the slots. CALL and RET
        # use that stack in a balanced way, so a nested call cannot disturb
        # what is already pushed.
        if any(_contains_call(arg) for arg in node.args[1:]):
            self.comment("a later argument calls something: stage via the stack")
            for arg in node.args:
                self._expr(arg)
                self.emit("PUSH A")
            for index in reversed(range(len(node.args))):
                self.emit("POP A")
                slot(index)
        else:
            for index, arg in enumerate(node.args):
                self._expr(arg)
                slot(index)

        if isinstance(node.callee, A.Identifier) and node.callee.symbol.storage == "function":
            target = node.callee.symbol.label
            if frame:
                self.emit(f"ADD F, F, #{frame}")
            self.emit(f"CALL {target}")
        else:
            self._expr(node.callee)             # a function pointer
            self.emit("MOV E, A")
            if frame:
                self.emit(f"ADD F, F, #{frame}")
            self.emit("CALL E")
        if frame:
            self.emit(f"SUB F, F, #{frame}")

    def _e_Index(self, node):
        self._address_of(node)
        if not isinstance(node.type, (ArrayType, StructType)):
            self.emit(f"{_load_op(node.type)} A, A")

    def _e_Member(self, node):
        self._address_of(node)
        if not isinstance(node.type, (ArrayType, StructType)):
            self.emit(f"{_load_op(node.type)} A, A")

    # --- addresses and storage ---------------------------------------------

    def _address_of(self, node: A.Node):
        """Leave the ADDRESS of an lvalue in A."""
        if isinstance(node, A.Identifier):
            symbol = node.symbol
            if symbol.storage in ("local", "param"):
                if symbol.offset:
                    self.emit(f"ADD A, F, #{symbol.offset}")
                else:
                    self.emit("MOV A, F")
            else:
                self.emit(f"MOV A, #{symbol.label}")
            return
        if isinstance(node, A.Unary) and node.op == "*":
            self._expr(node.operand)
            return
        if isinstance(node, A.Index):
            self._expr(node.base)
            self.emit("PUSH A")
            self._expr(node.index)
            self._scale(node.scale)
            self.emit("MOV B, A")
            self.emit("POP A")
            self.emit("ADD A, A, B")
            return
        if isinstance(node, A.Member):
            if node.arrow:
                self._expr(node.obj)
            else:
                self._address_of(node.obj)
            if node.field.offset:
                self.emit(f"ADD A, A, #{node.field.offset}")
            return
        raise node.token.error("cannot take the address of this expression")

    def _store_to(self, target: A.Node):
        """Store A into an lvalue, leaving A intact (assignment is an
        expression, and its value is what was assigned)."""
        if isinstance(target, A.Identifier) and target.symbol.storage in ("local", "param"):
            self._store_to_frame(target.symbol.offset, target.symbol.type)
            return
        if isinstance(target, A.Identifier):
            self.emit(f"MOV C, #{target.symbol.label}")
            self.emit(f"{_store_op(target.symbol.type)} C, A")
            return

        self.emit("PUSH A")                     # the value
        self._address_of(target)
        self.emit("MOV C, A")
        self.emit("POP A")
        self.emit(f"{_store_op(target.type)} C, A")

    def _load_from_frame(self, offset: int, type_):
        if offset == 0:
            self.emit(f"{_load_op(type_)} A, F")
            return
        self.emit(f"ADD C, F, #{offset}")
        self.emit(f"{_load_op(type_)} A, C")

    def _store_to_frame(self, offset: int, type_):
        if offset:
            self.emit(f"ADD C, F, #{offset}")
        else:
            self.emit("MOV C, F")
        self.emit(f"{_store_op(type_)} C, A")


def _load_op(type_) -> str:
    return "MR" if getattr(type_, "size", WORD) == 1 else "MRW"


def _store_op(type_) -> str:
    return "MW" if getattr(type_, "size", WORD) == 1 else "MWW"


def _invert(jump: str) -> str:
    return {"JZ": "JNZ", "JNZ": "JZ", "JL": "JGE",
            "JGE": "JL", "JG": "JLE", "JLE": "JG"}[jump]


def _contains_call(node) -> bool:
    """Does evaluating this expression call a function?

    Only matters for arguments: a call inside one overwrites the frame
    slots the enclosing call has already filled in.
    """
    if node is None or not isinstance(node, A.Node):
        return False
    if isinstance(node, A.Call):
        return True
    for value in vars(node).values():
        if isinstance(value, A.Node):
            if _contains_call(value):
                return True
        elif isinstance(value, list):
            if any(_contains_call(item) for item in value):
                return True
    return False


def _is_simple(node: A.Node) -> bool:
    """True when evaluating this cannot involve a call or deep nesting."""
    return isinstance(node, (A.IntLiteral, A.Identifier, A.StringLiteral))


def _escape_c(data: bytes) -> str:
    out = []
    for byte in data:
        if byte == 0x22:
            out.append('\\"')
        elif byte == 0x5C:
            out.append("\\\\")
        elif 0x20 <= byte <= 0x7E:
            out.append(chr(byte))
        else:
            out.append(f"\\x{byte:02X}")
    return "".join(out)


def generate(program: A.Program, source_lines=None) -> str:
    return CodeGen(program, source_lines).generate()
